# Generated by Django 4.2.1 on 2023-05-27 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_blog_rel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
