# Generated by Django 4.2.1 on 2023-06-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_blog_created_at_blog_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rel_Blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.blog"
                    ),
                ),
            ],
        ),
    ]
