# Generated by Django 4.2.1 on 2023-06-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_pubblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="publish_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="published_url",
            field=models.URLField(default="", max_length=100),
        ),
        migrations.DeleteModel(
            name="PubBlog",
        ),
    ]
