# Generated by Django 4.2.1 on 2023-06-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_blog_publish_active_blog_published_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verification",
        ),
    ]
