# Generated by Django 4.2.1 on 2023-06-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_user_email_verification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_verification",
            new_name="email_verif",
        ),
    ]
