# Generated by Django 4.2.1 on 2023-06-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_rename_email_verification_user_email_verif"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_verif",
            new_name="email_verification",
        ),
    ]
