# Generated by Django 4.2.1 on 2023-06-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_rename_email_verif_user_email_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Published",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "rel_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.blog"
                    ),
                ),
            ],
        ),
    ]
