# Generated by Django 4.2.1 on 2023-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="published",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=-1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="published",
            name="uid",
            field=models.CharField(max_length=100),
        ),
    ]
