# Generated by Django 4.2.1 on 2023-06-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_published_id_alter_published_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=100)),
                (
                    "rel_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.blog"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Published",
        ),
    ]
