# Generated by Django 4.2.1 on 2023-06-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_publish_delete_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Published",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, default=-1, primary_key=True, serialize=False
                    ),
                ),
                ("uid", models.CharField(max_length=100)),
                (
                    "rel_blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.blog"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Publish",
        ),
    ]
