# Generated by Django 4.2.1 on 2023-06-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_demourl"),
    ]

    operations = [
        migrations.AddField(
            model_name="demourl",
            name="rel_blog",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="main.blog"
            ),
            preserve_default=False,
        ),
    ]
