# Generated by Django 4.2.1 on 2023-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_rename_uid_demourl_demo_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.IntegerField(default=0),
        ),
    ]
